### ISSUE TITLE
API Failing as of July 1 2020 

### ISSUE THREAD

**Issue by rvnicholas** [facebookincubator/offline-conversion-file-uploader#25]
No changes our end however as of the July 1 we receive the below output (OAuthException).

It seems to create an infinite loop, returning the same error and process % does not increment.

![image](https://user-images.githubusercontent.com/39071730/86419711-65eab700-bd17-11ea-8bf7-5e3d241cf6fc.png)

**Comment by rvnicholas** [comment]
Further info: I've pulled the latest version of the code and am getting a different response:

API error: Invalid parameter

message":"Limited Data Use Selection Required: From July 1 to August 1, you must indicate whether usage should be limited for data sent via this API to be processed. You can learn how to implement Limited Data Use here - https://www.facebook.com/business/help/1151133471911882"
					,"type":"CodedException"
					,"code":2804030

I have reviewed the support information for this error here:

https://github.com/facebookincubator/offline-conversion-file-uploader/blob/master/offline-events/README.md

As per this link - I have added the following (last field) to our mapping:


and here:

https://developers.facebook.com/docs/marketing-apis/data-processing-options





FULL ERROR BELOW:

Error Details:

Using option accessToken:  <hidden>
Using option batchSize:  2000
Using option customTypeInfo:  {}
Using option dataSetID:  <hidden>
Using option delimiter:  ,
Using option format:  {
  "event_time": {
    "timeFormat": "ISO8601"
  },
  "dob": "DD/MM/YYYY"
}
Using option header:  true
Using option inputFilePath:  ..\one-click-test\test.csv
Using option logging:  verbose
Using option mapping:  {
  "0": "match_keys.email",
  "1": "match_keys.email",
  "2": "match_keys.phone",
  "3": "match_keys.phone",
  "4": "match_keys.phone",
  "5": "match_keys.fn",
  "6": "match_keys.ln",
  "7": "match_keys.ct",
  "8": "match_keys.st",
  "9": "match_keys.country",
  "10": "match_keys.dob",
  "11": "match_keys.doby",
  "12": "match_keys.age",
  "13": "match_keys.zip",
  "14": "event_time",
  "15": "event_name",
  "16": "value",
  "17": "currency",
  "18": "order_id",
  "19": "item_number",
  "20": "data_processing_options"
}
Using option presetValues:  {}
Using option reportOutputPath:  ..\one-click-test\SendReports"upload-report.txt"
Using option skipRowsAlreadyUploaded:  false
Using option apiVersion:  v6.0
Using option disableLogging:  true
Ignoring unsupported option data_processing_options. Please double check spelling and case.
2020-07-06T02:07:20.276Z INFO Config and logger initialized.
2020-07-06T02:07:20.831Z INFO Upload tag generated from file name and size.
2020-07-06T02:07:21.277Z INFO Found existing upload tag.
2020-07-06T02:07:21.277Z INFO Upload ID: <hidden>
2020-07-06T02:07:21.280Z INFO Upload Tag: test.csv (1876bytes)
2020-07-06T02:07:21.785Z WARN Batch [153, 1876): API error: Invalid parameter
2020-07-06T02:07:21.786Z WARN Error Details:
2020-07-06T02:07:21.793Z WARN
        {
			"0":
				{
					"event":
							{
								"currency":"AUD"
								,"event_name":"Purchase"
								,"event_time":1569592800
								,"item_number":""
								,"match_keys":
								{
									"country":"632cd2fea71dcde005af4e07f14b8bc1f68b63d9c1b373dc6048fb87e90af22b"
									,"ct":"3b2e7f404b860189ad0846fc46f1892aea241e93efbcd2138e2f3e0413d2b89b"
									,"dobd":"f5ca38f748a1d6eaf726b8a42fb575c3c71f1864a8143301782de13da2d9202b"
									,"dobm":"3514acf61732f662da19625f7fe781c3e483f2dce8506012f3bb393f5003e105"
									,"doby":"3510a92fc7dd04f69b1aeeef5489ef168dbf1d9c4d528b8f4af4240a8b295ab4"
									,"email":"e0e52a387081e93446af6ca3b343fb902c0ea1468e0a058c9bf771fd751e9acb"
									,"f5first":"a982c97d452cc71fde02409d6e6a623220c882930c3c13ab7733e61bc9870b6c"
									,"f5last":"f68af468e9c26669d5bda4310d25bba9c1fa23008a5afc9acb0fe6e589761b32"
									,"fi":"50e721e49c013f00c62cf59f2163542a9d8df02464efeb615d31051b0fddc326"
									,"fn":"a982c97d452cc71fde02409d6e6a623220c882930c3c13ab7733e61bc9870b6c"
									,"ln":"1aa779995b7a2b83dfe3a8727468535d1a04be7c2d7a9678d66ab53dd7c60a45"
									,"phone":"34b95a4d61dce21d17aa29ab33c00dc323b7fb95e8fc459d69c67a363c3dac30"
									,"st":"4cf6829aa93728e8f3c97df913fb1bfa95fe5810e2933a05943f8312a98d9cf2"
									,"zip":"43219ea99d4f6b23a85b1c0276ba48a3e6b8ce1e8a2131632f18643882f948ce"
								}
								,"order_id":"N19757"
								,"value":52970
							}
					,"event_index":0
					,"message":"Limited Data Use Selection Required: From July 1 to August 1, you must indicate whether usage should be limited for data sent via this API to be processed. You can learn how to implement Limited Data Use here - https://www.facebook.com/business/help/1151133471911882"
					,"type":"CodedException"
					,"code":2804030
				}
			}

**Comment by chaitu1124** [comment]
@rvnicholas  may i know how the issue resolved. I am also getting exact error message. I have added data_processing_options:[].

**Comment by chaitu1124** [comment]
@rvnicholas  - Thanks for your response. We have enabled the option and tried and getting the following error. 
We added the data_processing_options:[] in the data file.

Using option dataSetID:  236919390337098
Using option delimiter:  ,
Using option format:  {
  "doby": "YYYY",
  "event_time": {
    "timeFormat": "ISO8601"
  }
}
Using option header:  false
Using option inputFilePath:  ../../data/transactions/t1
Using option logging:  verbose
Using option mapping:  {
  "0": "match_keys.email",
  "1": "match_keys.fn",
  "2": "match_keys.ln",
  "3": "match_keys.fi",
  "4": "match_keys.zip",
  "5": "match_keys.ct",
  "6": "match_keys.st",
  "7": "match_keys.country",
  "8": "match_keys.doby",
  "9": "match_keys.gen",
  "10": "event_name",
  "11": "event_time",
  "12": "custom_data.p_traits",
  "13": "custom_data.channel",
  "14": "custom_data.t_cust",
  "15": "custom_data.t_traits",
  "16": "data_processing_options"
}
Using option presetValues:  {}
Using option reportOutputPath:  ../../data/logs/transactions/Verbose_t1.txt
Using option skipRowsAlreadyUploaded:  true
Ignoring unsupported option data_processing_options. Please double check spelling and case.
2020-08-25T20:21:30.976Z INFO Config and logger initialized.
2020-08-25T20:21:31.319Z ERROR ABORTED because more than 10% of the first 3 rows have errors.
2020-08-25T20:21:31.320Z INFO Report saved to: ../../data/logs/transactions/Verbose_t1.txt

Do you have any idea where it was wrong?

**Comment by rvnicholas** [comment]
I could never get the data processing options to be accepted, so I don’t trust the documentation at all….

I removed the processing options from the config completely (suggest you do the same)

Does your Verbose_t1.txt report give any further insight? It looks to me like there are issues with the data and the processing options warning can be ignored or removed by removing the options…

**Comment by chaitu1124** [comment]
@rvnicholas  - 

This is the one which we enabled. 

![image](https://user-images.githubusercontent.com/16243616/91337472-60eb3680-e7a1-11ea-8208-25e07fffcf08.png)

Verbose file is saying event_time and event_name is wrong. its same its not changed from the beginning. I think issue is some where else. I tried all possible options. Getting same error. If you are able to find any issue with this file, please let me know.

[Verbose_t1 (2).txt](https://github.com/facebookincubator/offline-conversion-file-uploader/files/5131453/Verbose_t1.2.txt)

**Comment by rvnicholas** [comment]
I'm unsure of the impact of the error log, in the past if our feed was being "Aborted" based on data errors, we had to correct them to resolve.

Regardless, I think you need to select "Keep default transition period", this is what we have in place.

Terrible implementation of this by FB IMO.
