### ISSUE TITLE
DatasetID - Where do I get that value?

### ISSUE THREAD

**Issue by evimed** [facebookincubator/offline-conversion-file-uploader#30]
Hi!

I am having trouble uploading offline conversions; specifically with the DatasetID parameter. 

Can you help me understand where this value comes from?

{"message":"Unsupported get request. Object with ID '20210721' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api","type":"GraphMethodException","code":100,"fbtrace_id":"Ajc4JUR51As_9ZuQtXNjJPt"}

Best,
   Antonio

**Comment by qgxqgx** [comment]
So , how did you handle this ?

**Comment by evimed** [comment]
This field has to be created at the Facebook side, using the Business
Manager tool.

Best,
   Antonio
